import type { Metadata } from "next";
import { inter } from "./fonts";
import "./globals.css";
import Navbar from "./ui/Navbar";

export const metadata: Metadata = {
  title: "Odin-Kittens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#000] antialiased px-5 max-w-[1000px] mx-auto`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
